version: '3.4'

services:
  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: pass

  migratedb:
    image: boxfuse/flyway:latest
    volumes:
      - ./flyway/sql:/flyway/sql
      - ./flyway/conf:/flyway/conf
    depends_on:
      - mysqldb
    command: migrate
